<?php
/**
 * Phone
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orders
 *
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Phone Class Doc Comment
 *
 * @category Class
 * @description The phone number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Phone implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'phone';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'country_code' => 'string',
        'national_number' => 'string',
        'extension_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'country_code' => null,
        'national_number' => null,
        'extension_number' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'country_code' => false,
		'national_number' => false,
		'extension_number' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_code' => 'country_code',
        'national_number' => 'national_number',
        'extension_number' => 'extension_number'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_code' => 'setCountryCode',
        'national_number' => 'setNationalNumber',
        'extension_number' => 'setExtensionNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_code' => 'getCountryCode',
        'national_number' => 'getNationalNumber',
        'extension_number' => 'getExtensionNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('national_number', $data ?? [], null);
        $this->setIfExists('extension_number', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country_code'] === null) {
            $invalidProperties[] = "'country_code' can't be null";
        }
        if ((mb_strlen($this->container['country_code']) > 3)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be smaller than or equal to 3.";
        }

        if ((mb_strlen($this->container['country_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[0-9]{1,3}?$/", $this->container['country_code'])) {
            $invalidProperties[] = "invalid value for 'country_code', must be conform to the pattern /^[0-9]{1,3}?$/.";
        }

        if ($this->container['national_number'] === null) {
            $invalidProperties[] = "'national_number' can't be null";
        }
        if ((mb_strlen($this->container['national_number']) > 14)) {
            $invalidProperties[] = "invalid value for 'national_number', the character length must be smaller than or equal to 14.";
        }

        if ((mb_strlen($this->container['national_number']) < 1)) {
            $invalidProperties[] = "invalid value for 'national_number', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[0-9]{1,14}?$/", $this->container['national_number'])) {
            $invalidProperties[] = "invalid value for 'national_number', must be conform to the pattern /^[0-9]{1,14}?$/.";
        }

        if (!is_null($this->container['extension_number']) && (mb_strlen($this->container['extension_number']) > 15)) {
            $invalidProperties[] = "invalid value for 'extension_number', the character length must be smaller than or equal to 15.";
        }

        if (!is_null($this->container['extension_number']) && (mb_strlen($this->container['extension_number']) < 1)) {
            $invalidProperties[] = "invalid value for 'extension_number', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['extension_number']) && !preg_match("/^[0-9]{1,15}?$/", $this->container['extension_number'])) {
            $invalidProperties[] = "invalid value for 'extension_number', must be conform to the pattern /^[0-9]{1,15}?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_code
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string $country_code The country calling code (CC), in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the CC and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        if ((mb_strlen($country_code) > 3)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling Phone., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($country_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling Phone., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[0-9]{1,3}?$/", $country_code))) {
            throw new \InvalidArgumentException("invalid value for \$country_code when calling Phone., must conform to the pattern /^[0-9]{1,3}?$/.");
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets national_number
     *
     * @return string
     */
    public function getNationalNumber()
    {
        return $this->container['national_number'];
    }

    /**
     * Sets national_number
     *
     * @param string $national_number The national number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the country calling code (CC) and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).
     *
     * @return self
     */
    public function setNationalNumber($national_number)
    {
        if (is_null($national_number)) {
            throw new \InvalidArgumentException('non-nullable national_number cannot be null');
        }
        if ((mb_strlen($national_number) > 14)) {
            throw new \InvalidArgumentException('invalid length for $national_number when calling Phone., must be smaller than or equal to 14.');
        }
        if ((mb_strlen($national_number) < 1)) {
            throw new \InvalidArgumentException('invalid length for $national_number when calling Phone., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[0-9]{1,14}?$/", $national_number))) {
            throw new \InvalidArgumentException("invalid value for \$national_number when calling Phone., must conform to the pattern /^[0-9]{1,14}?$/.");
        }

        $this->container['national_number'] = $national_number;

        return $this;
    }

    /**
     * Gets extension_number
     *
     * @return string|null
     */
    public function getExtensionNumber()
    {
        return $this->container['extension_number'];
    }

    /**
     * Sets extension_number
     *
     * @param string|null $extension_number The extension number.
     *
     * @return self
     */
    public function setExtensionNumber($extension_number)
    {
        if (is_null($extension_number)) {
            throw new \InvalidArgumentException('non-nullable extension_number cannot be null');
        }
        if ((mb_strlen($extension_number) > 15)) {
            throw new \InvalidArgumentException('invalid length for $extension_number when calling Phone., must be smaller than or equal to 15.');
        }
        if ((mb_strlen($extension_number) < 1)) {
            throw new \InvalidArgumentException('invalid length for $extension_number when calling Phone., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[0-9]{1,15}?$/", $extension_number))) {
            throw new \InvalidArgumentException("invalid value for \$extension_number when calling Phone., must conform to the pattern /^[0-9]{1,15}?$/.");
        }

        $this->container['extension_number'] = $extension_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


